### ISSUE TITLE
BitcoinInput.value is incorrect 

### ISSUE THREAD

**Issue by shihao-guo** [bitbart/blockchain-analytics-api#6]
When tracing the balance change of a single address, It looks like when the address exists in both tx.input and tx.output, and the block contains several transactions with the same situation, the BitcoinInput.value for that address is wrong for most of the cases. My guess is this has something to do with the BitcoinInput's UTXO map, but I can't find where the bug is.

You can try with the code [here](https://gist.github.com/shihao-guo/f82a86514fe6730050100c081afbc4dd) 

It will produce results like 

>  outval: 0.688235
in tx:b538d1faf9c9f1b065153273a877207b568d10690efb3c1da7093ddf419082d4
in block:468024
totalSent: 0.0
totalReceived: 133.52565
Diff: 0.688235
current balance:133.52565

> inval: 5.5948524
outval: 0.6592155
in tx:dc4ac84016ae4b92dd46690cfa6e11d4e2b49b8087aaf321f078eb8c9d4c17f3
in block:468024
totalSent: 5.5948524
totalReceived: 134.18486
Diff: -4.935637
current balance:128.59001

> inval: 6.625871
outval: 4.9852705
in tx:97a26ae395e3a5a54c08b72232d23dac3a3919369a9417236e7fd6a13b48a515
in block:468024
totalSent: 12.220723
totalReceived: 139.17014
Diff: -1.6406008
current balance:126.94942

> outval: 3.2955577
in tx:8221fdbc65c5cdfe80979e1e769c9ca633216250e32f4b3b550926531d204430
in block:468024
totalSent: 12.220723
totalReceived: 142.4657
Diff: 3.2955577
current balance:130.24498

> outval: 4.9572177
in tx:c0a74e489cb50e87e64469b78695bca1685a55d1ca9ec336fd47b13bbed3f2ed
in block:468024
totalSent: 12.220723
totalReceived: 147.42291
Diff: 4.9572177
current balance:135.2022

> outval: 2.1677854
in tx:64ea30022fd5c2612f2712002c88f742dfed8aaa548037084764d3e83907a2c5
in block:468024
totalSent: 12.220723
totalReceived: 149.5907
Diff: 2.1677854
current balance:137.36998

> outval: 0.46125695
in tx:53faacbde19e2193060d548f0bcc7cdb118844b1a64ed82bed5ce4c904c7fbf9
in block:468024
totalSent: 12.220723
totalReceived: 150.05196
Diff: 0.46125695
current balance:137.83124

> inval: 14.911379
outval: 4.949174
in tx:4de9f2ccb7d5ad1357f7479462a6d5b17b0eb6f67b4453b4c39e636444016fdc
in block:468024
totalSent: 27.132103
totalReceived: 155.00114
Diff: -9.962206
current balance:127.86903

> outval: 5.963515
in tx:516771dfe3f7b4bd2b83fc8ce0497539e3252fab39e5cb82a0f9ede2bdd086c1
in block:468024
totalSent: 27.132103
totalReceived: 160.96465
Diff: 5.963515
current balance:133.83255

> outval: 0.08214242
in tx:bb1320e34596ca32406dbce21180127bedbf602e78d46abb3b748c2f45a77bc7
in block:468024
totalSent: 27.132103
totalReceived: 161.0468
Diff: 0.08214242
current balance:133.91469

> inval: 8.897054
outval: 1.6960812
in tx:da36e0e17dbfd684c847223325f0330f69f83b5549344872cb6921e9ac13f57b
in block:468024
totalSent: 36.02916
totalReceived: 162.74287
Diff: -7.200973
current balance:126.713715

> outval: 0.06497606
in tx:6054f0a55bf9930edcaa8f91b23079ad175aeb967ee6f98edb2512aaf46cec66
in block:468024
totalSent: 36.02916
totalReceived: 162.80785
Diff: 0.06497606
current balance:126.778694

> inval: 6.1892066
outval: 0.8700876
in tx:16b221e1cb1b65bbb585db5edf936d6bed8ab04f5975af2b4e503628bfee719d
in block:468024
totalSent: 42.218365
totalReceived: 163.67793
Diff: -5.3191185
current balance:121.45957

> outval: 3.3412244
in tx:51bcb84a7a1ab3124e8aafd3f8e94d9d6f7e8d4095cb34f7d4ee36c27c406cd2
in block:468024
totalSent: 42.218365
totalReceived: 167.01917
Diff: 3.3412244
current balance:124.8008

> outval: 4.236634
in tx:c43c3d707c28f5987687702f175e1cad0512c256d73ecb632fcccb3e6317e72d
in block:468024
totalSent: 42.218365
totalReceived: 171.2558
Diff: 4.236634
current balance:129.03743

> inval: 24.661734
outval: 24.41348
in tx:9fbad998c23245c8f2f2dc8b8a5a3d4c5b5af45a56d63386558cd0228b9bfcf0
in block:468024
totalSent: 66.8801
totalReceived: 195.66928
Diff: -0.24825448
current balance:128.78917

Only the first and last case where the address exists in both input and output are correct according to [blockchain.info](https://blockchain.info/address/1N52wHoVR79PMDishab2XmRHsbekCdGquK?offset=50950&filter=6).

**Comment by stefanolande** [comment]
Hi Shihao,
did you find a bug in your code after opening the issue?

**Comment by shihao-guo** [comment]
yes it turns out there's a bug in my code that causes the UTXO references to be incorrect. That's why I closed this issue. Sorry for the confusion!

**Comment by LivioPompianu** [comment]
Hi Shihao,
no problem, thank you for contacting us!
